#!/bin/bash

COMPILER_PATH=$(dirname $0)/build/install/compiler/bin/compiler

if [ ! -f "$COMPILER_PATH" ]; then
    echo "${COMPILER_PATH} doesn't exist. Running './gradlew build'..."
    ./gradlew build
fi

"$COMPILER_PATH" $@
