#!/bin/bash

VERILOG_FORMAT_JAR_FILE_PATH=$(dirname $0)/verilog-format-1.0.1-full.jar
VERILOG_FORMAT_PROPERTIES_PATH=.verilog-format.properties

# Set the Internal Field Separator for bash so that \n is used as a delimiter
# in for loops.
IFS=$'\n'

# Loop through all arguments and format the specified files or recursively format 
# files in specified directories.
count=0
for path in "$@"; do
    if [ -d "$path" ]; then
        for subpath in $(find "$path" -iname *.v); do
            echo "Formatting ${subpath}."
            java -jar "$VERILOG_FORMAT_JAR_FILE_PATH" -f "$subpath" -s "$VERILOG_FORMAT_PROPERTIES_PATH"
            ((count++))
        done
    elif [ -f "$path" ]; then
        java -jar "$VERILOG_FORMAT_JAR_FILE_PATH" -f "$path" -s "$VERILOG_FORMAT_PROPERTIES_PATH"
        ((count++))
    else
        echo "$path does not exist." 1>&2;
    fi
done

echo "Formatted $count files."
